BASE_URL     = "https://dongcheyun.com"
OSS_URL      = "https://oss.dongcheyun.com"
DOC_URL      = "https://dongcheyun.com/p/56746"
DOC_ID       = "56746"
SYSTEM_TYPE  = "webpage"
OUTPUT_DIR   = "output"
COOKIES_FILE = "cookies.json"
USER_AGENT   = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36")